"""Forensic recovery of the missing selective-firewall breadth classifier.

Status
------
GREEN / RED / AMBER / sector_stress are mathematically recovered to exact
session-by-session parity with the frozen 7,061-session breadth oracle over
160,715 reconstructed holding-days.

The original `priority` score used by the selective cohort ranker has NOT yet
been exactly recovered.  This module therefore does not fabricate it.

Important numerical contract
----------------------------
`r21` and `r63` must be the values generated by the original position replay
(or an exactly equivalent implementation).  That replay stored lag closes in
float32 before dividing the current close by the lag.  Recomputing these
returns from all-float64 lag prices can alter exact-zero boundary cases.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Tuple

import numpy as np
import pandas as pd


@dataclass(frozen=True)
class RecoveredBreadthConfig:
    # Boundaries are intentionally explicit because strictness is material.
    green_own_dd_min_exclusive: float = -0.075
    green_r21_min_exclusive: float = 0.0
    green_r63_min_exclusive: float = 0.0
    green_r63_required_from_age: int = 63

    red_own_dd_max_inclusive: float = -0.10
    red_r21_max_exclusive: float = 0.0

    amber_own_dd_max_inclusive: float = -0.10
    amber_r21_max_inclusive: float = -0.03
    sector_stress_min_inclusive: float = 0.50


REQUIRED_COLUMNS = {
    "sector",
    "age_sessions",
    "own_dd",
    "r21",
    "r63",
}


def recovered_breadth_features(
    g: pd.DataFrame,
    cfg: RecoveredBreadthConfig = RecoveredBreadthConfig(),
) -> Tuple[pd.DataFrame, pd.Series]:
    """Return holding-level recovered health flags and sector stress.

    Returns
    -------
    x : DataFrame
        Copy of `g` with exact-recovered `green`, `red`, `sector_stress`, and
        `amber` columns.
    sector_stress : Series
        Per-sector fraction of RED holdings on this decision date.

    Notes
    -----
    `amber` is the holding-level label consumed downstream as `damaged` breadth.
    The original priority score is intentionally absent from this function.
    """
    missing = REQUIRED_COLUMNS.difference(g.columns)
    if missing:
        raise KeyError(f"Missing required columns: {sorted(missing)}")

    x = g.copy()

    # Exact recovered GREEN rule.
    # A holding younger than 63 completed sessions is not penalized for lacking
    # a valid 63-session ownership-history comparison.
    x["green"] = (
        (x["own_dd"] > cfg.green_own_dd_min_exclusive)
        & (x["r21"] > cfg.green_r21_min_exclusive)
        & (
            (x["age_sessions"] < cfg.green_r63_required_from_age)
            | (x["r63"] > cfg.green_r63_min_exclusive)
        )
    )

    # Exact recovered severe individual-damage subset.
    # Strict r21 < 0 is essential; r21 == 0 is NOT red.
    x["red"] = (
        (x["own_dd"] <= cfg.red_own_dd_max_inclusive)
        & (x["r21"] < cfg.red_r21_max_exclusive)
    )

    # Cross-sectional sector state is the RED fraction in each sector.
    sector_stress = x.groupby("sector", sort=False, dropna=False)["red"].mean()
    x["sector_stress"] = x["sector"].map(sector_stress).astype(float)

    # Exact recovered AMBER / damaged label.
    x["amber"] = (
        (x["own_dd"] <= cfg.amber_own_dd_max_inclusive)
        | (x["r21"] <= cfg.amber_r21_max_inclusive)
        | (
            (x["sector_stress"] >= cfg.sector_stress_min_inclusive)
            & (~x["green"])
        )
    )

    return x, sector_stress


def breadth_counts(g: pd.DataFrame) -> dict[str, int]:
    """Convenience helper for deterministic oracle comparison."""
    x, _ = recovered_breadth_features(g)
    return {
        "denominator": int(len(x)),
        "green": int(x["green"].sum()),
        "damaged": int(x["amber"].sum()),
        "red": int(x["red"].sum()),
    }


class PriorityNotRecoveredError(RuntimeError):
    pass


def position_features(g: pd.DataFrame, cfg=None):
    """Fail-closed compatibility entry point.

    The missing original function also returned a `priority` column.  Green,
    red, amber, and sector_stress are exact-recovered, but priority is not.
    Returning a guessed priority would silently change cohort selection, so this
    compatibility entry point deliberately refuses to masquerade as the full
    original function.
    """
    x, sector_stress = recovered_breadth_features(g)
    raise PriorityNotRecoveredError(
        "Breadth classification is exact-recovered, but original `priority` "
        "is not yet exact. Use recovered_breadth_features() for certified "
        "breadth reproduction; do not use a guessed priority in cohort ranking."
    )
