#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, os, shutil, subprocess, sys
from pathlib import Path
import pandas as pd

VARIANT='virtual-slot-free-cash'
BASELINE_SOURCE_SHA='740d353a223ab63112d5fb9c6eed1e6d7f8e69b1a6d2f46b83773df8f49daba6'
BASELINE_DAILY_SHA='bf1ecdc2917de2122904be2bb94b246d06e2a6927ad262a843333ee9d91823d1'
BASELINE_SUMMARY_SHA='753943497976027746b130d3afbe8365765800ab15d7284f993c3319bcbc984a'
START='2006-07-31'

def digest(p:Path): return hashlib.sha256(p.read_bytes()).hexdigest()
def repl(s,old,new,label):
    n=s.count(old)
    if n!=1: raise RuntimeError(f'{label}: expected one seam, got {n}')
    return s.replace(old,new,1)

def instrument(src:str)->str:
    s=src
    s=repl(s,"    pending_sell:bool=False; sell_reason:str=''; pending_tid:int=-1; pending_shares:float=0.; pending_signal_day:int=-1; pending_virtual:bool=False; pending_intended_capital:float=0.; virtual:bool=False; virtual_cash:float=0.; ready_day:int=0","    pending_sell:bool=False; sell_reason:str=''; pending_tid:int=-1; pending_shares:float=0.; pending_signal_day:int=-1; pending_virtual:bool=False; pending_intended_capital:float=0.; virtual:bool=False; virtual_cash:float=0.; audit_ep:int=-1; ready_day:int=0",'episode id')
    s=repl(s,"    rows=[]; overlap_checks={}; buys=sells=split_events=div_events=0; virtual_entries=virtual_releases=virtual_terminal_releases=virtual_stock_deliveries=virtual_decisions=virtual_gap_promotions=real_micro_executions=0; virtual_cash_locked_peak=0.0","    rows=[]; overlap_checks={}; buys=sells=split_events=div_events=0; virtual_entries=virtual_releases=virtual_terminal_releases=virtual_stock_deliveries=virtual_decisions=virtual_gap_promotions=real_micro_executions=0; virtual_cash_locked_peak=0.0\n    audit_daily=[]; audit_entries=[]; audit_exits=[]; audit_next_ep=0",'audit stores')
    s=repl(s,"                    _old_tid=s.tid; book.terminal_pending.pop(_old_tid,None)","                    _old_tid=s.tid; _old_ep=s.audit_ep; _old_qty=float(s.qty); _old_virtual=bool(s.virtual); book.terminal_pending.pop(_old_tid,None)",'terminal capture')
    s=repl(s,"                    if _kind in ('WRITE_OFF','CASH_MERGER') or int(_econ['delivered_shares'])<=0:\n                        if s.virtual: book.cash+=float(s.virtual_cash); virtual_terminal_releases+=1","                    if _kind in ('WRITE_OFF','CASH_MERGER') or int(_econ['delivered_shares'])<=0:\n                        if not _old_virtual and _old_ep>=0: audit_exits.append({'episode_id':int(_old_ep),'date':ds,'security_id':str(sid[_old_tid]),'ticker':str(tick[_old_tid]),'reason':'terminal_'+str(_kind).lower(),'qty':_old_qty,'exit_price':(float(_econ['cash'])/_old_qty if _old_qty>0 else None),'exit_proceeds':float(_econ['cash'])})\n                        if s.virtual: book.cash+=float(s.virtual_cash); virtual_terminal_releases+=1",'terminal cash')
    s=repl(s,"                        s.tid=-1; s.qty=0.; s.entry_sig=np.nan; s.peak=np.nan; s.entry_day=-1; s.reviewed=False; s.pending_sell=False; s.sell_reason=''; s.virtual=False; s.virtual_cash=0.; s.ready_day=gday+COOLDOWN","                        s.tid=-1; s.qty=0.; s.entry_sig=np.nan; s.peak=np.nan; s.entry_day=-1; s.reviewed=False; s.pending_sell=False; s.sell_reason=''; s.virtual=False; s.virtual_cash=0.; s.audit_ep=-1; s.ready_day=gday+COOLDOWN",'terminal reset')
    s=repl(s,"                        s.tid=int(_delivered); s.qty=float(_econ['delivered_shares'])\n                        if s.virtual: virtual_stock_deliveries+=1","                        if not _old_virtual and _old_ep>=0: audit_exits.append({'episode_id':int(_old_ep),'date':ds,'security_id':str(sid[_old_tid]),'ticker':str(tick[_old_tid]),'reason':'terminal_stock_delivery','qty':_old_qty,'exit_price':None,'exit_proceeds':float(_econ['cash'])})\n                        s.tid=int(_delivered); s.qty=float(_econ['delivered_shares'])\n                        if not s.virtual:\n                            s.audit_ep=audit_next_ep; audit_entries.append({'episode_id':int(audit_next_ep),'date':ds,'security_id':str(sid[int(_delivered)]),'ticker':str(tick[int(_delivered)]),'qty':float(s.qty),'entry_price':None,'entry_market_value':None,'entry_gross':None,'intended_capital':None,'funding_fraction':None,'entry_source':'stock_delivery'}); audit_next_ep+=1\n                        if s.virtual: virtual_stock_deliveries+=1",'stock delivery')
    s=repl(s,"                    _tid=s.tid; book.cash+=(float(s.virtual_cash) if s.virtual else s.qty*float(clraw[_tid])); virtual_terminal_releases+=int(s.virtual); book.sec_ready[_tid]=gday+COOLDOWN\n                    s.tid=-1; s.qty=0.; s.entry_sig=np.nan; s.peak=np.nan; s.entry_day=-1; s.reviewed=False; s.pending_sell=False; s.sell_reason=''; s.virtual=False; s.virtual_cash=0.; s.ready_day=gday+COOLDOWN","                    _tid=s.tid; _ep=s.audit_ep; _q=float(s.qty); _px=float(clraw[_tid]); book.cash+=(float(s.virtual_cash) if s.virtual else _q*_px); virtual_terminal_releases+=int(s.virtual); book.sec_ready[_tid]=gday+COOLDOWN\n                    if not s.virtual and _ep>=0: audit_exits.append({'episode_id':int(_ep),'date':ds,'security_id':str(sid[_tid]),'ticker':str(tick[_tid]),'reason':'terminal_current_mark','qty':_q,'exit_price':_px,'exit_proceeds':_q*_px})\n                    s.tid=-1; s.qty=0.; s.entry_sig=np.nan; s.peak=np.nan; s.entry_day=-1; s.reviewed=False; s.pending_sell=False; s.sell_reason=''; s.virtual=False; s.virtual_cash=0.; s.audit_ep=-1; s.ready_day=gday+COOLDOWN",'terminal current mark')
    s=repl(s,"                    if s.virtual:\n                        book.cash+=float(s.virtual_cash); virtual_releases+=1\n                    else:\n                        book.cash+=s.qty*float(px)*(1-COST); sells+=1\n                    if s.sell_reason=='stop': stop_days.append(gday)\n                    _sold_tid=s.tid; book.sec_ready[_sold_tid]=gday+COOLDOWN; book.terminal_pending.pop(_sold_tid,None)\n                    s.tid=-1; s.qty=0.; s.entry_sig=np.nan; s.peak=np.nan; s.entry_day=-1; s.reviewed=False; s.pending_sell=False; s.sell_reason=''; s.virtual=False; s.virtual_cash=0.; s.ready_day=gday+COOLDOWN","                    if s.virtual:\n                        book.cash+=float(s.virtual_cash); virtual_releases+=1\n                    else:\n                        _ep=s.audit_ep; _q=float(s.qty); _reason=str(s.sell_reason); _px=float(px); _proceeds=_q*_px*(1-COST); book.cash+=_proceeds; sells+=1\n                        if _ep>=0: audit_exits.append({'episode_id':int(_ep),'date':ds,'security_id':str(sid[s.tid]),'ticker':str(tick[s.tid]),'reason':_reason,'qty':_q,'exit_price':_px,'exit_proceeds':_proceeds})\n                    if s.sell_reason=='stop': stop_days.append(gday)\n                    _sold_tid=s.tid; book.sec_ready[_sold_tid]=gday+COOLDOWN; book.terminal_pending.pop(_sold_tid,None)\n                    s.tid=-1; s.qty=0.; s.entry_sig=np.nan; s.peak=np.nan; s.entry_day=-1; s.reviewed=False; s.pending_sell=False; s.sell_reason=''; s.virtual=False; s.virtual_cash=0.; s.audit_ep=-1; s.ready_day=gday+COOLDOWN",'normal exit')
    s=repl(s,"                            real_micro_executions+=int(_actual_fraction<0.01); book.cash-=q*float(px)*(1+COST); s.tid=tid; s.qty=float(q); s.entry_day=gday; s.reviewed=False; s.pending_sell=False; s.sell_reason=''; s.entry_sig=float(opsig[tid]) if finite(opsig[tid]) and opsig[tid]>0 else np.nan; s.peak=np.nan; book.initialized=True; buys+=1","                            real_micro_executions+=int(_actual_fraction<0.01); book.cash-=q*float(px)*(1+COST); s.tid=tid; s.qty=float(q); s.entry_day=gday; s.reviewed=False; s.pending_sell=False; s.sell_reason=''; s.entry_sig=float(opsig[tid]) if finite(opsig[tid]) and opsig[tid]>0 else np.nan; s.peak=np.nan; s.audit_ep=audit_next_ep; audit_entries.append({'episode_id':int(audit_next_ep),'date':ds,'security_id':str(sid[tid]),'ticker':str(tick[tid]),'qty':float(q),'entry_price':float(px),'entry_market_value':float(q)*float(px),'entry_gross':float(q)*float(px)*(1+COST),'intended_capital':float(s.pending_intended_capital),'funding_fraction':float(_actual_fraction),'entry_source':'buy'}); audit_next_ep+=1; book.initialized=True; buys+=1",'real entry')
    s=repl(s,"                book.cash+=(float(_slot.virtual_cash) if _slot.virtual else _slot.qty*float(_px)); virtual_terminal_releases+=int(_slot.virtual); book.sec_ready[_tid]=gday+COOLDOWN; book.terminal_pending.pop(_tid,None)\n                _slot.tid=-1; _slot.qty=0.; _slot.entry_sig=np.nan; _slot.peak=np.nan; _slot.entry_day=-1; _slot.reviewed=False; _slot.pending_sell=False; _slot.sell_reason=''; _slot.virtual=False; _slot.virtual_cash=0.; _slot.ready_day=gday+COOLDOWN","                _ep=_slot.audit_ep; _q=float(_slot.qty); _audit_px=float(_px); book.cash+=(float(_slot.virtual_cash) if _slot.virtual else _q*_audit_px); virtual_terminal_releases+=int(_slot.virtual); book.sec_ready[_tid]=gday+COOLDOWN; book.terminal_pending.pop(_tid,None)\n                if not _slot.virtual and _ep>=0: audit_exits.append({'episode_id':int(_ep),'date':ds,'security_id':str(sid[_tid]),'ticker':str(tick[_tid]),'reason':'terminal_c1_10_session_settlement','qty':_q,'exit_price':_audit_px,'exit_proceeds':_q*_audit_px})\n                _slot.tid=-1; _slot.qty=0.; _slot.entry_sig=np.nan; _slot.peak=np.nan; _slot.entry_day=-1; _slot.reviewed=False; _slot.pending_sell=False; _slot.sell_reason=''; _slot.virtual=False; _slot.virtual_cash=0.; _slot.audit_ep=-1; _slot.ready_day=gday+COOLDOWN",'c1 exit')
    s=repl(s,"            eq,unresolved=book.equity(clraw)\n            held=[]","            eq,unresolved=book.equity(clraw)\n            for _as in book.slots:\n                if not(_as.held() and not _as.virtual and _as.audit_ep>=0): continue\n                _at=int(_as.tid); _ap=clraw[_at]\n                if not(finite(_ap) and _ap>0): _ap=book.last_raw.get(_at,np.nan)\n                _av=(float(_as.qty)*float(_ap) if finite(_ap) and _ap>0 else None); _aw=(_av/float(eq) if _av is not None and finite(eq) and eq>0 else None)\n                audit_daily.append({'episode_id':int(_as.audit_ep),'date':ds,'security_id':str(sid[_at]),'ticker':str(tick[_at]),'qty':float(_as.qty),'close_price':(float(_ap) if finite(_ap) and _ap>0 else None),'position_value':_av,'portfolio_weight':_aw})\n            held=[]",'daily audit')
    s=repl(s,"    out=pd.DataFrame(rows)\n    out.to_csv(OUT/'daily.csv',index=False)","    pd.DataFrame(audit_daily).to_csv(OUT/'position-audit-daily.csv',index=False)\n    pd.DataFrame(audit_entries).to_csv(OUT/'position-entry-events.csv',index=False)\n    pd.DataFrame(audit_exits).to_csv(OUT/'position-exit-events.csv',index=False)\n    out=pd.DataFrame(rows)\n    out.to_csv(OUT/'daily.csv',index=False)",'audit output')
    compile(s,'<audited>','exec'); return s

def summarize(output:Path, engine:Path):
    d=pd.read_csv(engine/'position-audit-daily.csv'); e=pd.read_csv(engine/'position-entry-events.csv'); x=pd.read_csv(engine/'position-exit-events.csv')
    for z in (d,e,x): z['date']=pd.to_datetime(z['date'])
    xm={int(r.episode_id):r for _,r in x.iterrows()}; rows=[]
    for _,a in e.sort_values('episode_id').iterrows():
        ep=int(a.episode_id); q=d[d.episode_id==ep].sort_values('date'); z=xm.get(ep)
        if not len(q) or q.date.max()<pd.Timestamp(START): continue
        if z is not None and z.date<pd.Timestamp(START): continue
        v=pd.to_numeric(q.position_value,errors='coerce'); w=pd.to_numeric(q.portfolio_weight,errors='coerce'); first=q.iloc[0]; last=q.iloc[-1]
        rows.append({'episode_id':ep,'ticker':str(a.ticker),'security_id':str(a.security_id),'entry_date':a.date.date().isoformat(),'exit_date':(z.date.date().isoformat() if z is not None else None),'exit_reason':(str(z.reason) if z is not None else 'OPEN_END'),'entry_source':str(a.entry_source),'entry_qty':float(a.qty),'entry_price':(None if pd.isna(a.entry_price) else float(a.entry_price)),'entry_size_dollars':(None if pd.isna(a.entry_market_value) else float(a.entry_market_value)),'entry_gross_dollars':(None if pd.isna(a.entry_gross) else float(a.entry_gross)),'intended_entry_capital':(None if pd.isna(a.intended_capital) else float(a.intended_capital)),'entry_funding_fraction':(None if pd.isna(a.funding_fraction) else float(a.funding_fraction)),'entry_close_size_dollars':(None if pd.isna(first.position_value) else float(first.position_value)),'entry_close_portfolio_weight':(None if pd.isna(first.portfolio_weight) else float(first.portfolio_weight)),'minimum_size_dollars_while_held':float(v.min()),'maximum_size_dollars_while_held':float(v.max()),'minimum_portfolio_weight_while_held':float(w.min()),'maximum_portfolio_weight_while_held':float(w.max()),'final_size_dollars':(None if pd.isna(last.position_value) else float(last.position_value)),'final_portfolio_weight':(None if pd.isna(last.portfolio_weight) else float(last.portfolio_weight)),'exit_price':(None if z is None or pd.isna(z.exit_price) else float(z.exit_price)),'exit_proceeds_dollars':(None if z is None or pd.isna(z.exit_proceeds) else float(z.exit_proceeds))})
    audit=pd.DataFrame(rows); audit.to_csv(output/'POSITION_TRADE_AUDIT.csv',index=False)
    buys=e[e.entry_source=='buy']; bad=buys[pd.to_numeric(buys.funding_fraction,errors='coerce')<0.01]; measured=d[d.date>=pd.Timestamp(START)].copy(); pw=pd.to_numeric(measured.portfolio_weight,errors='coerce'); pv=pd.to_numeric(measured.position_value,errors='coerce'); threshold=.04*.01; tiny=measured[pw<threshold]; extreme=measured[pw<.0001]
    r={'schema':'research.wealth-core-v1-virtual-slot-position-audit/1','status':'PASS','variant':VARIANT,'position_episodes_overlapping_measurement':int(len(audit)),'real_buy_entries':int(len(buys)),'real_entry_below_1pct_of_intended_count':int(len(bad)),'micro_portfolio_threshold':threshold,'real_daily_observations_below_micro_portfolio_threshold_count':int(len(tiny)),'episodes_ever_below_micro_portfolio_threshold':int(tiny.episode_id.nunique()),'real_daily_observations_below_0_01pct_portfolio_count':int(len(extreme)),'episodes_ever_below_0_01pct_portfolio':int(extreme.episode_id.nunique()),'minimum_real_portfolio_weight_observed':float(pw.min()),'minimum_real_position_value_observed':float(pv.min()),'daily_sha256':digest(engine/'daily.csv'),'summary_sha256':digest(engine/'summary.json')}
    if r['daily_sha256']!=BASELINE_DAILY_SHA or r['summary_sha256']!=BASELINE_SUMMARY_SHA: raise RuntimeError('audit instrumentation changed candidate economics')
    if len(bad): raise RuntimeError('real microscopic entry survived')
    (output/'AUDIT_RESULT.json').write_text(json.dumps(r,indent=2,sort_keys=True)+'\n')
    for f in ('position-audit-daily.csv','position-entry-events.csv','position-exit-events.csv'): shutil.copy2(engine/f,output/f)
    return r

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--candidate-root',type=Path,required=True); ap.add_argument('--engine',type=Path,required=True); ap.add_argument('--output',type=Path,required=True); a=ap.parse_args()
    sys.path.insert(0,str(Path(__file__).resolve().parent.parent/'wealth-core-v1-virtual-slot-v1'))
    from virtual_patch import patch_source,sha,CONTROL_SOURCE_SHA256,CONTROL_NORMALIZED_AST_SHA256,DATASET_SHA256
    from backtester import champion_full_classification_control as control
    from backtester.production_equivalent_economic_overlay import install,assert_contract,assert_one_session_dividend_lag
    from backtester.champion_economic_prefix_audit import normalized_ast
    eng=a.engine.resolve(); out=a.output.resolve(); eng.mkdir(parents=True,exist_ok=True); out.mkdir(parents=True,exist_ok=True)
    if json.loads((Path(os.environ['CANONICAL_PIT_DATASET'])/'manifest.json').read_text()).get('dataset_hash')!=DATASET_SHA256: raise RuntimeError('dataset mismatch')
    _,_,prior=control.build_source(eng,a.candidate_root.resolve()); v1=install(prior); assert_contract(v1)
    if sha(v1.encode())!=CONTROL_SOURCE_SHA256 or sha(normalized_ast(v1).encode())!=CONTROL_NORMALIZED_AST_SHA256: raise RuntimeError('V1 mismatch')
    base=patch_source(v1,VARIANT); assert_contract(base)
    if sha(base.encode())!=BASELINE_SOURCE_SHA: raise RuntimeError('free-cash candidate source mismatch')
    src=instrument(base); assert_contract(src)
    if assert_one_session_dividend_lag(src)!=1: raise RuntimeError('dividend contract changed')
    p=out/'audited-generated.py'; p.write_text(src)
    env=os.environ.copy(); env['RESEARCH_REPLAY_MODE']='fullpit'; subprocess.run([sys.executable,str(p)],cwd=Path.cwd(),env=env,check=True)
    r=summarize(out,eng); print('[POSITION_AUDIT] '+json.dumps(r,sort_keys=True),flush=True)
if __name__=='__main__': main()
