"""Disabled-by-default durable orchestration for Sentinel paper trading.

Importing this package performs no database, clock, network, or broker action.
"""
from sentinel.automation.model import (
    AckState,
    AlertRecord,
    AlertState,
    AutomationConfig,
    AutomationControl,
    AutomationRefused,
    CallbackDeadlineExceeded,
    CancellationAuthority,
    ControlBinding,
    CycleContext,
    CycleRecord,
    CycleSpec,
    CycleState,
    DataIntegrityFailure,
    DispatchResult,
    ExecuteDisposition,
    ExecuteResult,
    ImmutableAlertChanged,
    ImmutableCycleChanged,
    InvalidCycleTransition,
    HumanInterventionRequired,
    LeaderPermit,
    MissingAutomationState,
    NonRetryableCallbackRefused,
    PermanentOperationalRefusal,
    PrepareResult,
    RefreshResult,
    SessionSchedule,
    SoftwareDefect,
    SupervisorIntegrityFailure,
    StaleLeaderRefused,
    TickAction,
    TickResult,
    TransientInfrastructureFailure,
)

__all__ = [
    "AckState", "AlertRecord", "AlertState", "AutomationConfig",
    "AutomationControl", "AutomationRefused", "CallbackDeadlineExceeded",
    "CancellationAuthority",
    "ControlBinding",
    "CycleContext", "CycleRecord", "CycleSpec", "CycleState",
    "DataIntegrityFailure",
    "DispatchResult", "ExecuteDisposition", "ExecuteResult",
    "ImmutableAlertChanged", "ImmutableCycleChanged",
    "HumanInterventionRequired", "InvalidCycleTransition", "LeaderPermit",
    "MissingAutomationState", "NonRetryableCallbackRefused",
    "PermanentOperationalRefusal", "PrepareResult", "RefreshResult",
    "SessionSchedule", "SoftwareDefect", "SupervisorIntegrityFailure",
    "StaleLeaderRefused", "TickAction",
    "TickResult", "TransientInfrastructureFailure",
]
