#!/usr/bin/env python3
"""Supply a disposable SQL prerequisite to the repository's full-suite runner."""
from __future__ import annotations

import os
import json
import re
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT), str(ROOT / "shared")]

from tests.support.postgres import _EphemeralPostgres
from tests.internal_state.image_gate import IMAGE_TESTS, image_verdict

# Identical to the existing prospective Wealth Core gate on main. No hashes or
# expected economics are regenerated by this harness.
HISTORICAL_EXCLUSIONS = (
    "tests/wealth_core/test_golden_fixture.py::test_the_result_matches_the_pinned_fixture",
    "tests/wealth_core/test_golden_fixture.py::TestTheHashesAreInterpreterIndependent::test_the_run_hash_is_stable_in_a_FRESH_INTERPRETER",
    "tests/wealth_core/test_performance_integration.py::test_measuring_does_not_move_the_pinned_result_hash",
)


def image_contract():
    """Build the real pinned artifact and run its six mandatory import checks."""
    output = ROOT / "artifacts/runtime-contract"
    output.mkdir(parents=True, exist_ok=False)
    commit = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    runtime = "sentinel-state-runtime:" + commit[:12]
    test_image = "sentinel-state-tests:" + commit[:12]
    report = {"verdict": "FAIL", "commit": commit, "expected": list(IMAGE_TESTS)}
    try:
        if subprocess.check_output(["git", "status", "--porcelain", "--untracked-files=no"],
                                   cwd=ROOT, text=True).strip():
            raise RuntimeError("runtime gate requires a clean tested commit")
        for dockerfile, tag, extra in (
            ("Dockerfile.sentinel", runtime, []),
            ("Dockerfile.sentinel-test", test_image, ["--build-arg", "SENTINEL_IMAGE=" + runtime]),
        ):
            subprocess.run(["docker", "build", "--build-arg", "SOURCE_GIT_SHA=" + commit,
                *extra, "-f", dockerfile, "-t", tag, "."], cwd=ROOT, check=True)
        report["runtime_image_id"] = subprocess.check_output(
            ["docker", "image", "inspect", runtime, "--format", "{{.Id}}"], text=True).strip()
        if re.fullmatch(r"sha256:[0-9a-f]{64}", report["runtime_image_id"]) is None:
            raise RuntimeError("runtime image id is missing or invalid")
        result = subprocess.run(["docker", "run", "--rm", "--network", "none",
            "--entrypoint", "python", "-v", str(output) + ":/evidence", test_image,
            "-m", "pytest", *IMAGE_TESTS, "-q", "-ra", "--junitxml=/evidence/runtime.xml"], cwd=ROOT)
        report.update(image_verdict(output / "runtime.xml", exitstatus=result.returncode))
    except Exception as exc:
        report["error"] = repr(exc)
    (output / "verdict.json").write_text(json.dumps(report, sort_keys=True, indent=2) + "\n")
    return 0 if report["verdict"] == "PASS" else 1


def main():
    server = _EphemeralPostgres()
    try:
        server.start()
        env = dict(os.environ, SENTINEL_DATABASE_URL=server.sync_dsn,
                   ALPACA_HARNESS_REQUIRE_POSTGRES="1",
                   SENTINEL_PUBLICATION_RECEIPT_KEY="internal-state-suite-synthetic-receipt-key",
                   INTERNAL_STATE_SUITE_EVIDENCE="artifacts/suites",
                   PYTEST_ADDOPTS="-p tests.internal_state.ci_gate")
        args = ["bash", "scripts/run-tests.sh", "-q", "-ra"]
        for node in (*HISTORICAL_EXCLUSIONS, *IMAGE_TESTS):
            args += ["--deselect", node]
        host_status = subprocess.run(args, cwd=ROOT, env=env).returncode
        artifact_status = image_contract()
        return int(host_status != 0 or artifact_status != 0)
    finally:
        server.stop()


if __name__ == "__main__":
    raise SystemExit(main())
