#!/usr/bin/env python3
"""Supply a disposable SQL prerequisite to the repository's full-suite runner."""
from __future__ import annotations

import os
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT), str(ROOT / "shared")]

from tests.support.postgres import _EphemeralPostgres

# Identical to the existing prospective Wealth Core gate on main. No hashes or
# expected economics are regenerated by this harness.
HISTORICAL_EXCLUSIONS = (
    "tests/wealth_core/test_golden_fixture.py::test_the_result_matches_the_pinned_fixture",
    "tests/wealth_core/test_golden_fixture.py::TestTheHashesAreInterpreterIndependent::test_the_run_hash_is_stable_in_a_FRESH_INTERPRETER",
    "tests/wealth_core/test_performance_integration.py::test_measuring_does_not_move_the_pinned_result_hash",
)


def main():
    server = _EphemeralPostgres()
    try:
        server.start()
        env = dict(os.environ, SENTINEL_DATABASE_URL=server.sync_dsn,
                   ALPACA_HARNESS_REQUIRE_POSTGRES="1",
                   INTERNAL_STATE_SUITE_EVIDENCE="artifacts/suites",
                   PYTEST_ADDOPTS="-p tests.internal_state.ci_gate")
        args = ["bash", "scripts/run-tests.sh", "-q", "-ra"]
        for node in HISTORICAL_EXCLUSIONS:
            args += ["--deselect", node]
        return subprocess.run(args, cwd=ROOT, env=env).returncode
    finally:
        server.stop()


if __name__ == "__main__":
    raise SystemExit(main())
